[package]
name = "unixml_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
nom = "7.1.3"
thiserror = "1.0.40"
#xml_oxide = "0.3.0"
